# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Caleb Stanford

# Short description (goes below the title; it will also be used in the RSS feed)
description: Personal website and blog

# Your name, as you want it to appear underneath each post and in the footer
author: Caleb Stanford

# Your email if you want it to be linked on the contact page
author_email: castan at cis upenn edu

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
# baseurl: /blog

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://cdstanford.github.io

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
# markdown: rdiscount
# markdown: maruku # recommended for use with MathJax. See this website: http://haixing-hu.github.io/programming/2013/09/20/how-to-use-mathjax-in-jekyll-generated-github-pages/.
markdown: kramdown

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
## Pagination sucks! It doesn't work anywhere except index.html. How silly.
# gems: [jekyll-paginate]
# paginate: 5
# paginate_path: "page:num"

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Override the default excerpt behavior by customizing the excerpt separator.
excerpt_separator: <!--EXCERPT TO HERE-->
# Now the excerpt will be the entire post, unless the above is included.
